# Generated by Django 3.1 on 2020-12-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_experience_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
