# Generated by Django 3.1 on 2020-12-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_project_proj_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='exp_type',
            field=models.CharField(choices=[('Intern', 'Intern'), ('', '')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_category',
            field=models.CharField(choices=[('All', 'all'), ('App', 'app'), ('Web', 'web')], default='all', max_length=10),
        ),
    ]
