# Generated by Django 3.1 on 2020-12-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20201228_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
