# Generated by Django 3.1 on 2020-12-29 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutHeader', models.CharField(max_length=255)),
                ('aboutItalic', models.CharField(max_length=100)),
                ('aboutPara', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.admin')),
            ],
        ),
    ]
