# Generated by Django 3.1 on 2020-12-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aboutItalic',
            field=models.CharField(max_length=255),
        ),
    ]
